### PR TITLE
Added 'dts:parent' property to Navigation endpoint.

### PR DESCRIPTION
**Pull request by monotasker**
This pull request addresses issue #186  by adding the `dts:parent` property to the returned JSON objects from Navigation endpoint requests.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Hmm, I actually think I'd rather have a Reference object here. `{"id", "ref", "start", "end"}` with the possibility of a null value for ref ?

**Comment by monotasker** [comment]
Alright, I've added a new commit to this pull request that revises the proposed dts:parent implementation in keeping with our discussions and adds it to all of the examples. (I've also added some clarifying [?] changes to the text here and there--couldn't help myself!)

Note that this proposal assumes Hugh's model in which a range has no parent. If we want to adopt the alternative of a range having a parent range, I'll need some clarification on the format for specifying that parent range and its type.

**Comment by PonteIneptique** [comment]
@monotasker That's a great job from what I read. I'd prefer that we finish our discussion on https://github.com/distributed-text-services/specifications/issues/194 before merging but I think that's a great step :D

**Review by balmas — COMMENTED** [review]
this looks good to me, although I am confused by the reference to multiple parents, which I thought wasn't supported?

**Comment by monotasker** [comment]
Okay, I just added another commit that does these things following our meeting discussion today:
- changes the type of reference objects in "dts:parent" from "Reference" to "CitableUnit"
- rewrites the sections on response scheme and URL parameters for clarity and especially to make clearer the meanings of the "level" parameter vs. the "dts:level" response property.
- added a line to the opening of the Navigation documentation clarifying for newcomers how it relates to the Collections endpoint.

I should probably be creating separate issues/prs for these other rewrites, since they don't directly address the "parent" issue. Sorry!

**Comment by monotasker** [comment]
Okay, I'm not sure where you're at with this right now @PonteIneptique:
 
1. In the latest commit the reference to multiple parents is removed. 
2. The format [null] is what was agreed on two meetings ago and put in the minutes. If people want that changed to the simple null, that's fine.
3. The type is given already on the parent property in every example. Although I made other changes, this PR is just trying to implement "parent." I don't mind adding the type elsewhere in the examples, although that's addressing a different issue. Where exactly do you mean the type should be added? Are you wanting the @dts:CiteType property added to the response object in every example? Or are you wanting an additional type declared for the response objects themselves? If it's the latter, we haven't decided on the format for that, have we?

So the upshot, as far as I can see, is that the current commit implements what we've agreed on for the "parent" property. If we want to change [null] to just null, I'm happy to do that if the others agree. Beyond that, I'd rather not hold up this PR until we implement other changes. The type on the response objects, for example, isn't something the group has agreed on, is it?

**Comment by PonteIneptique** [comment]
Finally coming back to this !

The only issue that remains I think is the `[null]` when there are no parents. Given that we decided that `dts:parent` can only be a single parent, it really feels weird to me that we stay on our decision to have `List[null]`. I do believe `null` is better here... Shall we update our decision on this on Friday meeting or can people vote here ? @hcayless @balmas @jonathanrobie ?

**Review by PonteIneptique — APPROVED** [review]

**Pull request merged**
