### PR TITLE
Add view property for handling pagination

### PR DESCRIPTION
**Pull request by monotasker**
Add a `view` property to returned Navigation and Collection/Resource objects if the response is paginated. Added `PartialCollectionView` and `PartialNavigationView` object types for the values of the `view` property.

**NB:** This PR is cumulative depending on the previous PR harmonizing the Resource object properties.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
@monotasker Is there any reason to duplicate the type of views ? They have the same props :)

**Comment by monotasker** [comment]
I don't really see one, no. We had a type in our example that was named specifically for collections, and I just didn't think about changing the type name to make it more generic :D Shall I amalgamate the two types with something like `PartialResultsView` as the type?

**Comment by PonteIneptique** [comment]
PaginationObject would be clear enough no ?

**Comment by monotasker** [comment]
Yep. And maybe a bit clearer.Sent from my iPhoneOn Aug 7, 2024, at 5:36 PM, Thibault Clérice ***@***.***> wrote:﻿
PaginationObject would be clear enough no ?

**Comment by PonteIneptique** [comment]
Actually, just Pagination, because we did not call thing resourceobject

**Comment by monotasker** [comment]
Done. The two new types have been amalgamated as one `Pagination` type. I left a list of its properties on both endpoints for convenience, but highlighted on Navigation that the definition is reapeated from Collection (with a link).

**Pull request merged**
